# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abc064a05cb2fc1e9fed76bced34ac3616ed6051a5456abf5efae721a0a95862e68ce960289bca341563d1892de3c1d1fc58b4b0fc40f6e7fdfcdd9a0de0a515

test:
  secret_key_base: a50d69992820daea4057a988770a039a09ccb11c72f60e517171ddfae016a051dedc4789cac2ac24023b43579e8458359fb2d007648bd73327c110efd791b27b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
